CREATE TABLE `letters` (
	`id` int AUTO_INCREMENT NOT NULL,
	`authorId` int NOT NULL,
	`recipientName` varchar(100),
	`recipientRelation` varchar(50),
	`audioUrl` varchar(500),
	`audioDuration` int,
	`transcription` text,
	`aiDraft` text,
	`finalContent` text NOT NULL,
	`templateUsed` varchar(50),
	`isEncrypted` boolean NOT NULL DEFAULT true,
	`encryptionIv` varchar(255) NOT NULL,
	`ciphertextUrl` varchar(500) NOT NULL,
	`proofHash` varchar(64) NOT NULL,
	`proofProvider` varchar(50) DEFAULT 'local',
	`txHash` varchar(66),
	`proofCreatedAt` timestamp,
	`unlockAt` timestamp,
	`unlockPolicy` varchar(50) DEFAULT 'datetime',
	`isUnlocked` boolean NOT NULL DEFAULT false,
	`unlockedAt` timestamp,
	`keyShard1` text,
	`keyShard2` text,
	`keyShard3` text,
	`status` varchar(20) NOT NULL DEFAULT 'draft',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `letters_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(50) NOT NULL,
	`displayName` varchar(100) NOT NULL,
	`description` text,
	`prompt` text NOT NULL,
	`recordingPrompt` text NOT NULL,
	`exampleOneLiner` text,
	`icon` varchar(50),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `templates_id` PRIMARY KEY(`id`),
	CONSTRAINT `templates_name_unique` UNIQUE(`name`)
);
